# Generated by Django 4.2.26 on 2025-11-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name', max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='Device IP address')),
                ('port', models.IntegerField(default=4370, help_text='Device port (default 4370)')),
                ('enabled', models.BooleanField(default=True, help_text='Is device enabled for polling')),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='User/Employee ID from device', max_length=50)),
                ('timestamp', models.DateTimeField(db_index=True, help_text='Punch timestamp')),
                ('status', models.IntegerField(help_text='Punch status code')),
                ('punch_state', models.IntegerField(default=0, help_text='Punch state')),
                ('verify_type', models.IntegerField(default=0, help_text='Verification type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_attendances', to='core.device')),
            ],
            options={
                'verbose_name': 'Raw Attendance',
                'verbose_name_plural': 'Raw Attendances',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='core_rawatt_user_id_96839c_idx'), models.Index(fields=['device', 'timestamp'], name='core_rawatt_device__e1fc5b_idx')],
                'unique_together': {('device', 'user_id', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='ProcessedAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='User/Employee ID', max_length=50)),
                ('date', models.DateField(db_index=True, help_text='Attendance date')),
                ('clock_in', models.DateTimeField(blank=True, help_text='Clock-in timestamp (earliest punch)', null=True)),
                ('clock_out', models.DateTimeField(blank=True, help_text='Clock-out timestamp (latest punch)', null=True)),
                ('is_outlier', models.BooleanField(default=False, help_text='Flagged as outlier')),
                ('outlier_reason', models.TextField(blank=True, help_text='Reason for outlier flag')),
                ('synced_to_crm', models.BooleanField(default=False, help_text='Synced to CRM')),
                ('sync_attempts', models.IntegerField(default=0, help_text='Number of sync attempts')),
                ('last_sync_attempt', models.DateTimeField(blank=True, help_text='Last sync attempt timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_attendances', to='core.device')),
            ],
            options={
                'verbose_name': 'Processed Attendance',
                'verbose_name_plural': 'Processed Attendances',
                'ordering': ['-date', 'user_id'],
                'indexes': [models.Index(fields=['user_id', 'date'], name='core_proces_user_id_37ea49_idx'), models.Index(fields=['date', 'synced_to_crm'], name='core_proces_date_f444f8_idx'), models.Index(fields=['synced_to_crm', 'sync_attempts'], name='core_proces_synced__667ed9_idx')],
                'unique_together': {('device', 'user_id', 'date')},
            },
        ),
    ]
