# Generated by Django 4.2.26 on 2025-11-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='User/Employee ID from device', max_length=50, unique=True)),
                ('name', models.CharField(help_text="User's full name", max_length=100)),
                ('privilege', models.IntegerField(default=0, help_text='User privilege level')),
                ('password', models.CharField(blank=True, help_text='User password', max_length=50)),
                ('group_id', models.CharField(blank=True, help_text='User group ID', max_length=50)),
                ('card_no', models.CharField(blank=True, help_text='Card number', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(help_text='Source device', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.device')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['user_id'],
            },
        ),
    ]
