# Generated by Django 4.2.26 on 2026-01-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='secondary_ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Secondary IP address (failover)', null=True),
        ),
    ]
