# Generated by Django 4.2.26 on 2026-01-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_device_secondary_ip_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='DeviceUser',
        ),
        migrations.AlterModelOptions(
            name='deviceuser',
            options={'ordering': ['user_id'], 'verbose_name': 'Device User', 'verbose_name_plural': 'Device Users'},
        ),
        migrations.AlterField(
            model_name='deviceuser',
            name='device',
            field=models.ForeignKey(help_text='Source device', on_delete=django.db.models.deletion.CASCADE, related_name='device_users', to='core.device'),
        ),
    ]
