# Generated by Django 4.2.26 on 2026-01-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_user_to_deviceuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='timezone',
            field=models.CharField(default='Africa/Nairobi', help_text='Device timezone (e.g., Africa/Nairobi, UTC)', max_length=50),
        ),
    ]
