# Generated by Django 4.2.26 on 2026-01-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_device_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedattendance',
            name='is_early_departure',
            field=models.BooleanField(default=False, help_text='Punched out early'),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='is_late_arrival',
            field=models.BooleanField(default=False, help_text='Punched in late'),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='is_outlier',
            field=models.BooleanField(default=False, help_text='Flagged as outlier (unclassifiable punch outside shift window)'),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='outlier_reason',
            field=models.TextField(blank=True, help_text='Reason for outlier/late/early flags'),
        ),
    ]
