# Generated by Django 4.2.26 on 2026-01-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_late_early_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedattendance',
            name='is_incomplete',
            field=models.BooleanField(default=False, help_text='Missing clock-in or clock-out'),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='outlier_reason',
            field=models.TextField(blank=True, help_text='Reason for outlier/late/early/incomplete flags'),
        ),
    ]
