# Generated by Django 4.2.26 on 2026-01-15 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_incomplete_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlierPunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='User/Employee ID', max_length=50)),
                ('punch_datetime', models.DateTimeField(db_index=True, help_text='Actual punch timestamp')),
                ('reason', models.TextField(help_text='Why this is an outlier')),
                ('associated_shift_date', models.DateField(blank=True, help_text='Potential shift date', null=True)),
                ('reviewed', models.BooleanField(default=False, help_text='Has been reviewed by admin')),
                ('notes', models.TextField(blank=True, help_text='Admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Outlier Punch',
                'verbose_name_plural': 'Outlier Punches',
                'ordering': ['-punch_datetime'],
            },
        ),
        migrations.AlterModelOptions(
            name='processedattendance',
            options={'ordering': ['-shift_date', 'user_id'], 'verbose_name': 'Processed Attendance', 'verbose_name_plural': 'Processed Attendances'},
        ),
        migrations.AlterUniqueTogether(
            name='processedattendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='earliest_punch',
            field=models.DateTimeField(blank=True, help_text='First punch within shift window', null=True),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='latest_punch',
            field=models.DateTimeField(blank=True, help_text='Last punch within shift window', null=True),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes'),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='punch_count',
            field=models.IntegerField(default=0, help_text='Number of punches within shift window'),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='shift_date',
            field=models.DateField(blank=True, db_index=True, help_text='Shift date (when shift starts)', null=True),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Expected shift end time', null=True),
        ),
        migrations.AddField(
            model_name='processedattendance',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Expected shift start time', null=True),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='clock_in',
            field=models.DateTimeField(blank=True, help_text='LEGACY: use earliest_punch', null=True),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='clock_out',
            field=models.DateTimeField(blank=True, help_text='LEGACY: use latest_punch', null=True),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='date',
            field=models.DateField(blank=True, db_index=True, help_text='LEGACY: use shift_date', null=True),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='is_incomplete',
            field=models.BooleanField(default=False, help_text='Missing punch within shift window'),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='is_outlier',
            field=models.BooleanField(default=False, help_text='LEGACY: outliers now in OutlierPunch table'),
        ),
        migrations.AlterField(
            model_name='processedattendance',
            name='outlier_reason',
            field=models.TextField(blank=True, help_text='LEGACY: moved to OutlierPunch'),
        ),
        migrations.AlterUniqueTogether(
            name='processedattendance',
            unique_together={('device', 'user_id', 'shift_date')},
        ),
        migrations.AddIndex(
            model_name='processedattendance',
            index=models.Index(fields=['user_id', 'shift_date'], name='core_proces_user_id_c17563_idx'),
        ),
        migrations.AddIndex(
            model_name='processedattendance',
            index=models.Index(fields=['shift_date', 'synced_to_crm'], name='core_proces_shift_d_c750ea_idx'),
        ),
        migrations.AddField(
            model_name='outlierpunch',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlier_punches', to='core.device'),
        ),
        migrations.AddIndex(
            model_name='outlierpunch',
            index=models.Index(fields=['user_id', 'punch_datetime'], name='core_outlie_user_id_d95a27_idx'),
        ),
        migrations.AddIndex(
            model_name='outlierpunch',
            index=models.Index(fields=['punch_datetime', 'reviewed'], name='core_outlie_punch_d_86d025_idx'),
        ),
        migrations.AddIndex(
            model_name='outlierpunch',
            index=models.Index(fields=['associated_shift_date'], name='core_outlie_associa_888113_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outlierpunch',
            unique_together={('device', 'user_id', 'punch_datetime')},
        ),
    ]
