# Generated by Django 4.2.26 on 2026-01-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_restructure_attendance_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceuser',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name (preferred for display)", max_length=200),
        ),
        migrations.AlterField(
            model_name='deviceuser',
            name='name',
            field=models.CharField(help_text="User's name from device", max_length=100),
        ),
    ]
